"""MCP server for Faithful evaluation using the MCP SDK."""

from __future__ import annotations

import logging
import os

from dotenv import load_dotenv
from mcp.server.fastmcp import FastMCP

from faithfulai.config import FaithfulAIConfig, LLMProvider
from faithfulai.pipeline import FaithfulAIPipeline

# Load environment variables
load_dotenv()

logger = logging.getLogger("faithful_ai")

# Create the MCP server
mcp = FastMCP(name="faithfulai")

# Global pipeline instance (lazy-initialized)
_pipeline: FaithfulAIPipeline | None = None


def _get_pipeline() -> FaithfulAIPipeline:
    """Get or create the shared pipeline instance."""
    global _pipeline
    if _pipeline is None:
        provider_str = os.environ.get("LLM_PROVIDER", "groq").lower()
        provider = LLMProvider(provider_str) if provider_str in ["groq", "openai", "anthropic"] else LLMProvider.GROQ

        config = FaithfulAIConfig(
            llm_provider=provider,
            llm_model=os.environ.get("LLM_MODEL", "llama-3.3-70b-versatile"),
            llm_api_key=None,  # Will be read from env
            hf_api_token=None,  # Will be read from env
        )
        _pipeline = FaithfulAIPipeline(config)
        logger.info("Pipeline initialized for MCP server")

    return _pipeline


@mcp.tool()
async def evaluate_faithfulness(query: str, rag_answer: str, sources: list[str]) -> dict:
    """Evaluate the faithfulness of a RAG-generated answer against source documents.

    This tool analyzes whether the provided answer is supported by the given
    source documents, detecting hallucinations and relevance drift.

    Args:
        query: The original user question.
        rag_answer: The answer generated by the RAG system.
        sources: A list of source documents used to generate the answer.

    Returns:
        A dictionary containing the evaluation score, flags, and detailed explanations.
    """
    pipeline = _get_pipeline()
    result = await pipeline.evaluate(query, rag_answer, sources)
    return result.model_dump()


def main() -> None:
    """Run the MCP server using stdio transport."""
    logger.info("Starting FaithfulAI MCP server")
    mcp.run(transport="stdio")


if __name__ == "__main__":
    main()
